project("MyriadTest" VERSION 0.0.1 DESCRIPTION "A test for the Myriad Game Engine")
cmake_minimum_required(VERSION "3.18.4")
set(CMAKE_VERBOSE_MAKEFILE TRUE)
set(CXX_STANDARD 17)
if(CMAKE_SYSTEM_NAME EQUAL Windows)
target_link_options(-static-libgcc -lopengl32 -lgdi32 -lwinmm)
endif()
#set_target_properties("MyriadTest" PROPERTIES CMAKE_CXX_STANDARD 17)
file(GLOB_RECURSE TEST_SOURCES CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
add_executable("MyriadTest" "${TEST_SOURCES}")
target_include_directories("MyriadTest" PUBLIC "../Engine/src")
target_link_libraries("MyriadTest" PRIVATE MyriadEngine)
#target_link_libraries("MyriadTest" MyriadEngine)
