cmake_minimum_required(VERSION "3.18.4")
project("MyriadTest")
set(CMAKE_VERBOSE_MAKEFILE TRUE)
set(CMAKE_CXX_STANDARD 17)
file(GLOB_RECURSE TEST_SOURCES CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
add_executable("MyriadTest" "${TEST_SOURCES}")
target_include_directories("MyriadTest" PUBLIC "../Engine/src")
#target_link_libraries("MyriadTest" PRIVATE MyriadEngine)
target_link_libraries("MyriadTest" MyriadEngine)
